// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	site: 'https://unidesktop.sr-studio.cn',
	devToolbar: { enabled: false },
	// The hand-written documentation pages were replaced by the official
	// UniDesktop doc set, so keep the old public paths resolving.
	redirects: {
		'/zh-cn/guides/example': '/zh-cn/getting-started/installation/',
		'/zh-cn/reference/example': '/zh-cn/reference/platform-support/',
		'/en/guides/example': '/en/getting-started/installation/',
		'/en/reference/example': '/en/reference/platform-support/',
	},
	integrations: [
		starlight({
			title: 'UniDesktop',
			favicon: '/unidesktop-logo.png',
			logo: {
				src: './public/unidesktop-logo.png',
			},
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/UniDesktop' }],
			sidebar: [
				{
					label: 'Getting started',
					translations: { 'zh-CN': '快速开始' },
					items: [{ autogenerate: { directory: 'getting-started' } }],
				},
				{
					label: 'Guides',
					translations: { 'zh-CN': '功能指南' },
					items: [{ autogenerate: { directory: 'guides' } }],
				},
				{
					label: 'Reference',
					translations: { 'zh-CN': '参考手册' },
					items: [{ autogenerate: { directory: 'reference' } }],
				},
				{
					label: 'Internals',
					translations: { 'zh-CN': '内部实现' },
					// Listed explicitly rather than autogenerated: Starlight derives
					// an autogenerated group's label from the directory name, which
					// would surface the nested `protocols` directory verbatim in both
					// languages. Explicit slugs take each page's own localized title.
					items: [
						{ slug: 'internals/architecture' },
						{ slug: 'internals/contributing' },
						{ slug: 'internals/fallback-engine' },
						{
							label: 'Protocols',
							translations: { 'zh-CN': '协议' },
							items: [
								{ slug: 'internals/protocols' },
								{ slug: 'internals/protocols/dbusmenu' },
								{ slug: 'internals/protocols/notifyicon' },
								{ slug: 'internals/protocols/portal' },
								{ slug: 'internals/protocols/statusnotifieritem' },
							],
						},
					],
				},
			],
			defaultLocale: 'zh-cn',
			locales: {
				en: {
					label: 'English',
					lang: 'en-US',
				},
				'zh-cn': {
					label: '简体中文',
					lang: 'zh-CN',
				},
		},
		}),
	],
});
